appName: soul
listen: 0.0.0.0
port: 8080
log:
  level: DEBUG
  console: true
  path: "./app.log"
  rotate:
    # 单个文件最大大小, 单位M
    maxSize: 50
    # 最多保留多少个文件
    maxBackups: 10
    # 每个最多保留多少天
    maxAge: 10
    # 轮转后压缩
    compress: false
    localtime: true
